name: Squeezelite
version: "1.0.4"
slug: squeezelite
description: Turn your Home Assistant into a Squeezelite media player
url: "https://github.com/freundTech/hassio-addon-squeezelite/tree/main/squeezelite"
image: "ghcr.io/freundtech/{arch}-addon-squeezelite"
arch:
  - aarch64
  - amd64
init: false
audio: true
realtime: true
options:
  player_name: "Home Assistant"
schema:
  player_name: "str"
  mac_address: "str?"
